#!/bin/bash

# Get instance metadata and save as variable
METADATA=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/?recursive=true&alt=json")

# Use jq to convert metadata to JSON format
JSON=$(echo $METADATA | jq -c '.')

# Output JSON
echo $JSON
